version: "3.9"
services:
  rabbitmq-local:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "dev1234"
      RABBITMQ_DEFAULT_PASS: "dev1234"
      RABBITMQ_DEFAULT_VHOST: "/"

  api-event-message:
    build:
      context: Api_Event_Message
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-local
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq-local:5672
    depends_on:
      - rabbitmq-local