spring:
  application:
    name: api-event-message
  rabbitmq:
    host: 127.0.0.1 #localhost
    port: 5672
    username: dev1234
    password: dev1234
    virtual-host: /
    dynamic:  true
    publisher-returns: true

server:
  port: 9001
queue-params:
  queue: event-message
  durable: false
  autodelete: true